### ISSUE TITLE
problem with arduino uno

### ISSUE THREAD

**Issue by Hirashi3630** [fb39ca4/kappa-pad#2]
Hi, i did it same like you but every time when i do it, it say this error: https://gyazo.com/78b2ed2c9332870db752b15d1be16ce8
Can someone help me?
sorry for bad eng owo

**Comment by fb39ca4** [comment]
The Arduino Uno doesn't have the ability to act as a USB keyboard by default. However, you could try Hoodloader2 to gain the ability to reprogram the ATMega16U2 (the chip driving the USB-Serial interface to the main ATMega328P microcontroller) and just run the kappa-pad code on that chip.
